---
apiVersion: v1
kind: Secret
metadata:
  name: test10-repo
  namespace: openshift-gitops
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/janus-backstage/test10-gitops.git
